### ISSUE TITLE
Timing for run sequence

### ISSUE THREAD

**Issue by Fresheyeball** [purescript-contrib/gulp-purescript#11]
Not sure if this is on gulp-purescript or is some other problem, but take a look at this [**file.**](https://github.com/CapillarySoftware/purescript-timers/blob/master/gulpfile.js#L41)
The `2000ms` timeout is my work around for `'test:unit'` firing before its ready. It seems like gulp-purescript is not accurately reporting when work is completed.

**Comment by ethul** [comment]
@Fresheyeball Have you seen this error crop up again on the newest `gulp-purescript` version? Thanks!

**Comment by ethul** [comment]
Closing. We can reopen or bring up a new issue if we start seeing this again.
