### ISSUE TITLE
Feature request, .psci task

### ISSUE THREAD

**Issue by Fresheyeball** [purescript-contrib/gulp-purescript#12]
Grunt purescript has a .psci task. It would be nice if it was here as well.

**Comment by craigdallimore** [comment]
@ethul 

A bit of feedback - or rather, a call for aid - mostly because I'm very new to purescript and I'm a bit unclear on how this feature is intended to be used:

Would you mind providing an example config / a bit of advice? I'm doing this -
```
gulp.task('purescript', function() {

  // config.puresript.src is an array like so:
  // [  'bower_components/purescript-*/src/**/*.purs*',
  //    'src/**/*.purs'                                                           
  // ]  


  return gulp.src(config.purescript.src)                                        
    .pipe(purescript.psc({                                                      
      noPrelude : false,                                                        
      main      : 'Example',                                                         
      dotPsci   : config.purescript.src
    }))                                                                        
    .pipe(rename('bundle.js'))                                                  
    .pipe(gulp.dest('dist'));

});
```
... but I'm not clear if I have produced a valid configuration. I _do_ find I have a `.psci` file generated:
```
cat .psci
:m bower_components/purescript-math/src/Math.purs
```
Is this valid content? What should be in here? From psci I find I _can_ load the module I have in bower_components, should I also be able to load a module (`Example`) from `src`?

Thank you in advance :)

**Comment by ethul** [comment]
@craigdallimore 

Thanks for checking out `gulp-purescript`!

Your setup looks pretty good to me. The only issue I see pertains to the `dotPsci` option being passed to `psc`.

To generate a `.psci` file, we have to create a separate gulp task. Usually I write it as follows.

```javascript
gulp.task('psci', function(){
  return gulp.src(config.purescript.src).
         pipe(purescript.dotPsci());
});
```

And you're right, the `.psci` file will contain entries like:
```bash
:m bower_components/purescript-transformers/src/Control/Monad/Writer/Trans.purs
:m src/Data/Coyoneda.purs
:m src/Data/Yoneda.purs
:m src/Control/Comonad/Cofree.purs
:m src/Control/Monad/Free.purs
```

The files after `:m` should be those in your project and their dependencies, basically the files in `config.purescript.src`.

If you're interested in a complete `gulp-purescript` example, the following might be helpful.
https://github.com/ethul/purescript-reactf/blob/master/gulpfile.js

I don't actually have a `psc` task in that file, but if you have any questions just let me know.

**Comment by craigdallimore** [comment]
@ethul Thank you for the advice and the example! :)

**Comment by ethul** [comment]
Welcome!
