### ISSUE TITLE
Use local psc

### ISSUE THREAD

**Issue by kRITZCREEK** [purescript-contrib/gulp-purescript#19]
Now that purescript is [npm installable](https://www.npmjs.com/package/purescript) it would be nice if **gulp-purescript** checked for a local installation of purescript in node_modules before invoking the global installation.
This could work similar to how bodil's ```pulp dep``` uses the locally installed bower before invoking a global installation.

This would have the benefits that one could depend on a specific version of the compiler and would also reduce global installs.

**Comment by ethul** [comment]
Agreed. I will take a look!

**Comment by kRITZCREEK** [comment]
You're fantastic :+1:

**Comment by ethul** [comment]
:)
