### ISSUE TITLE
Binaries installed by npm don't seem to work on Windows

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/gulp-purescript#21]
I'm not exactly sure what the problem is here, I'll try and figure it out when I can, but wanted to make a note so I don't forget. Attempting to use any of the tasks results in this:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn Unknown system errno 193
    at errnoException (child_process.js:998:11)
    at Process.ChildProcess._handle.onexit (child_process.js:789:34)
```

**Comment by ethul** [comment]
Thanks for the heads up.

I don't have a convenient way to test on windows, but would you be able to try modifying [this line](https://github.com/purescript-contrib/gulp-purescript/blob/6b8a4be93dcd33d62ba9527718fd90c084c59a40/index.js#L64) to be something like:

`child_process.spawn('Full\Windows\Path\To\node.exe ' + bin, args)`

I am guessing the issue has something to do with windows not understanding the [shabang line](https://github.com/purescript-contrib/node-purescript-bin/blob/master/bin/psc.js#L1).

**Comment by garyb** [comment]
Ah yep, that looks like it. I had push `bin` into `args`, but that works, and in fact, just spawning "node" works:
```
child_process.spawn('node', [bin].concat(args))
```

**Comment by ethul** [comment]
Thanks for the test and confirmation. I will push a patch tonight or tomorrow.

**Comment by ethul** [comment]
@garyb would you please be able to confirm if the fix is working as expected? I've released it in `0.3.1`

Thanks!

**Comment by garyb** [comment]
Will do! I don't have access to my Windows machine right now but can test this evening.

**Comment by ethul** [comment]
Great, thanks!

**Comment by garyb** [comment]
:ok_hand:

**Comment by ethul** [comment]
Thanks!
