### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/gulp-purescript#35]
@ethul could you publish the version with the changes for psc 0.7 please? We're going to make an RC soon, and it would be good to have a usable gulp version to go with it. If we release it as `0.5.0-rc` it shouldn't ensure that people don't end up installing it by accident too, as I believe NPM will favour the non-postifxed release.

**Comment by ethul** [comment]
Done. On npm as `0.5.0-rc.1`.

**Comment by garyb** [comment]
Thanks! :+1: 

Unfortunately `npm i gulp-purescript` does fetch `0.5.0-rc.1`, but at least it won't break anything, apart from the new argument it should be backwards compatible.

**Comment by ethul** [comment]
Welcome. And agreed that it should be okay if the latest is fetched.
