### ISSUE TITLE
Error: no writecb in Transform class

### ISSUE THREAD

**Issue by farnoy** [purescript-contrib/gulp-purescript#37]
Hi,

I'm setting up for purescript development and I've had gulp already, so I tried this:

```
gulp = require("gulp")
purescript = require("gulp-purescript")

gulp.task "purescript", ->
  gulp.src("./src/*.purs")
    .pipe(purescript.psc())
    .pipe(gulp.dest("./build/purescript"))
```

I get 
```
[12:35:07] Using gulpfile /data/chat/frontend/gulpfile.coffee
[12:35:07] Starting 'purescript'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: no writecb in Transform class
```

And if I remove the `pipe(gulp.dest(...))` call
 ```
[12:37:05] Starting 'purescript'...
[12:37:05] 'purescript' errored after 36 ms
[12:37:05] Error in plugin 'gulp-purescript'
Message:
    Type mismatch: expected object, found undefined
```

**Comment by farnoy** [comment]
Alright nevermind, specifying the main module in `psc(...)` has fixed the issue.

**Comment by ethul** [comment]
Glat it works. I will take a look at that error message. It looks like the underlying error is being hidden. Thanks for the report.

**Comment by porglezomp** [comment]
In addition to looking at the error message, the example gulpfile should probably be changed to a valid one, since it causes this same error.

**Comment by ethul** [comment]
@porglezomp Good catch on the README. I've opened #42 for this.

**Comment by porglezomp** [comment]
Also, one final gotcha, it would be nice the `module:` argument was more permissive and treated `'Main'` the same as `['Main']`. This probably won't matter much once the error messages are fixed though.

On the topic of the error message, while I was searching around and running into bug reports on other plugins, I found multiple references to exceptions not being caught by the plugin and bubbling up to a catchall somewhere inside gulp itself that produces the bad error message.

**Comment by ethul** [comment]
Let's get a fix in for the error messages first and see how that goes. If we need more flexibility in the type of the module argument we can look into adding that afterwards. And good to know about the catchall. I will do some digging on this.
