### ISSUE TITLE
Update to use compiler globbing

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/gulp-purescript#38]
As mentioned in #36, Windows sucks. Er, I mean has a limit on the length of a command, and as of purescript/purescript#1155 the compiler now supports glob arguments directly for input source files. 

I'd suggest now we should move away from piping `gulp.src(...)` into the tasks, and just make a `src` option argument - this way globbing for `ffi` and `src` can behave consistently for the compiler's glob behaviour (which may subtly differ from gulp's), and will also solve our path length problem.

Passing through `gulp.src` will unavoidably expand the globs (I think), so I don't know if there is another way to solve the path issue other than this. We may still have issues with `cross-spawn` and this, as that seems to impose an extremely short path length, but it will be a step in the right direction at least.

**Comment by ethul** [comment]
Thanks @garyb. I agree that we will probably have to pass the glob arguments as options instead of piping the files with `gulp.src`. Regarding `cross-spawn`, we can see how it goes. If it is still causing an issue, we can maybe find an alternative.
