### ISSUE TITLE
Support ffi in dotPsci

### ISSUE THREAD

**Issue by sharkdp** [purescript-contrib/gulp-purescript#40]
It would be nice if the `dotPsci` task would also support the `ffi` option. It would add
```
:f path/to/module.js
```
lines to the `.psci` file to load the corresponding foreign code when running `psci`.

**Comment by ethul** [comment]
Agreed. I will add this in conjunction with the changes for #38 

Thanks!

**Comment by sharkdp** [comment]
Great, thanks!
