### ISSUE TITLE
Warnings are hidden

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/gulp-purescript#51]
Currently no warnings are printed by the `psc` task, I think this comes from the change to reduce the verbosity of the output.

**Comment by ethul** [comment]
Good catch. Does it work adding the --verbose flag?

**Comment by garyb** [comment]
Yep, that brings them through.

I think the `psc` verbosity has toned down a lot since the output was silenced - it only dumps reading/writing messages when its own verbose flag is enabled now, so we might be able to just show the whole output again anyway.

**Comment by ethul** [comment]
Thanks for checking. We could flip the argument to --silent. I will take a look.

**Comment by garyb** [comment]
As of the new `v0.7.2` release warning are printed to `stderr` rather than `stdout` if that makes things any easier?

**Comment by ethul** [comment]
Thanks for the heads up @garyb. Warnings should now be displayed properly.

**Comment by garyb** [comment]
Great! Thanks for the quick turnaround. I can see just how many little mistakes I'm making now :wink:

**Comment by ethul** [comment]
Welcome, glad it works!
