### ISSUE TITLE
Setting browserNameSpace throws an error

### ISSUE THREAD

**Issue by yemi** [purescript-contrib/gulp-purescript#53]
I get `Error: Usage: psc-bundle FILE [-o|--output ARG] [-m|--module ARG] [--main ARG] [-n|--namespace ARG]` when setting `browserNameSpace` to any string.

**Comment by ethul** [comment]
Good catch. Looks like `browserNamespace` has to be migrated to `namespace`.

**Comment by ethul** [comment]
Should be corrected in version 0.7.0. If you have a chance to test it out, that would be great.
