### ISSUE TITLE
Windows: The command line is too long.

### ISSUE THREAD

**Issue by xavierzwirtz** [purescript-contrib/gulp-purescript#55]
On Windows when trying to use `gulp-purescript` to compile you will get an error message:
```
The command line is too long.
```
If I modify my `gulp-purescript` version to log the full arguments to the console I can see that the total command length is 11320 characters, greater than Windows max length of 8192.

The way the `gulp-tsc` project [solved this](https://github.com/kotas/gulp-tsc/pull/34) is by saving the arguments to a temporary text file, and then passing the path to that text file to the typescript compiler.

**Comment by xavierzwirtz** [comment]
This will require a change to `psc` as well to get it to read arguments from a text file.
[Corresponding `psc` issue.](https://github.com/purescript/purescript/issues/1575)

**Comment by garyb** [comment]
See #36. We changed the plugin to use psc's glob patterns.

**Comment by xavierzwirtz** [comment]
Aaand I was using a horrifically old version of `gulp-purescript`. That fixes it.

**Comment by garyb** [comment]
Ah right :smile: that's a relief, I did think we had resolved this a while ago.

**Comment by xavierzwirtz** [comment]
I am getting started with purescript, there is a [bootstrap project](https://github.com/nicholaskariniemi/purescript-bootstrap) that is using a very old version of `gulp-purescript`. Thanks for the help.
