### ISSUE TITLE
Add option to set number of threads psc will use

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/gulp-purescript#56]
Ideally this should be something we can read from the command line args rather than something that is set in the gulpfile.

The motivation for this is to limit the threads used on Travis, at it seems whatever default it is using is crippling the compiler performance currently (10x slower at compiling `purescript-halogen`), as of psc 0.7.5.

I'm only thinking of the RTS `-N` option here, but maybe we should allow the use of any RTS arguments, it could be useful for debugging too.

**Comment by ethul** [comment]
Good idea!

**Comment by garyb** [comment]
Resolved by #57
