### ISSUE TITLE
How to add --json-errors flag?

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [purescript-contrib/gulp-purescript#59]
atom ide-purescript requires that we pass --json-errors flag to psc. How do we do that in our gulpfile?

**Comment by ethul** [comment]
Currently `gulp-purescript` doesn't support the `--json-errors` option.

We would have to add it to the [`Psc` option type](https://github.com/purescript-contrib/gulp-purescript/blob/52586ec380d74172226042bd2098d7fd98fd716c/src/GulpPurescript/Options.purs#L83). I should be able to make this addition soon, but if you're interested in submitting a PR for the change, it would most welcome!
