### ISSUE TITLE
RTS options only affect compile

### ISSUE THREAD

**Issue by kenkku** [purescript-contrib/gulp-purescript#65]
I'm not sure if this is a bug or intended behavior, but the RTS options passed to Gulp only have an effect on the `compile` command. We are using `-N2` to reduce problems in CircleCI, but since the RTS flags are only applied to the compile command, bundling takes almost 3 minutes.

Maybe the RTS options could be applied to bundle as well, or an option could be added to specify RTS flags when calling the plugin from JS?

**Comment by garyb** [comment]
Yeah, that's an accident for sure. Looks like it'd be easy enough to fix, just need to add the `rtsOpts` to the specific options for each task, similar to https://github.com/purescript-contrib/gulp-purescript/blob/0563deb9763f7411c4b2081efbb55364e4b299b0/src/GulpPurescript/Plugin.purs#L123
